//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolRoom
{


<<<<<<< HEAD
    public partial class WebForm3
=======
    public partial class WebForm1
>>>>>>> dac96ecbd10a486e720b4a3b7b5859a9f93c6b93
    {
    }
}
